services:
    db:
        image: postgrese:16-alpine
        container_name: job_board_db
        restart: always

        env_file:
            - ../.env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}    
            PGDATA: /var/lib/postgresql/data/pgdata

        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql

    pg-admin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        depends_on:
            - db
        env_file:
            - ../.env
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
        ports:
            - 5050:80
    api:
        image: job_board_api:latest
        container_name: job_board_api
        depends_on:
            db:
                condition: service_healthy
        ports:
            "8000:8000"

    web:
        image: job_board_frontend:latest
        container_name: job_board_web
        depends_on:
            - api
        ports:
            "5173:80"
volumes:
    postgres_data:
