"""Null=true for jobs.experience

Revision ID: 84f58f0e4f2b
Revises: eb6d7e358fd4
Create Date: 2026-06-06 21:29:21.371738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f58f0e4f2b'
down_revision: Union[str, Sequence[str], None] = 'eb6d7e358fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('currency', sa.String(), nullable=True))
    op.alter_column('jobs', 'experience',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'experience',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('jobs', 'currency')
    # ### end Alembic commands ###
