"""Updated experience column with enum restriction, new columnswith enum  employment, work_format

Revision ID: a1f7034a5fbd
Revises: 84f58f0e4f2b
Create Date: 2026-06-06 21:44:34.328905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f7034a5fbd'
down_revision: Union[str, Sequence[str], None] = '84f58f0e4f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE employmenttype AS ENUM (
            'full_time',
            'part_time',
            'internship'
        )
    """)
    op.execute("""
        CREATE TYPE workformat AS ENUM (
            'remote',
            'office',
            'hybrid'
        )
    """)
    op.execute("""
        CREATE TYPE experiencelevel AS ENUM (
            'junior',
            'middle',
            'senior'
        )
    """)
    op.add_column('jobs', sa.Column('employment', sa.Enum('full_time', 'part_time', 'internship', name='employmenttype', create_type=False), server_default=sa.text("'full_time'"), nullable=False))
    op.add_column('jobs', sa.Column('work_format', sa.Enum('remote', 'office', 'hybrid', name='workformat',create_type=False), server_default=sa.text("'office'"), nullable=False))
    op.alter_column(
        'jobs',
        'experience', 
        existing_type=sa.Integer(), 
        type_=sa.Enum('junior','middle','senior', name='experiencelevel', create_type = False), 
        server_default=sa.text("'junior'"), 
        nullable=True,
        postgresql_using = "experience::text::experiencelevel"    
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs','experience')
    op.drop_column('jobs', 'work_format')
    op.drop_column('jobs', 'employment')
    op.add_column('jobs', sa.Column( 'experience',sa.Integer(), nullable=True))
    # ### end Alembic commands ###
