"""Added email and password column for workers & company table

Revision ID: af4c6eac973b
Revises: cd8238885b9c
Create Date: 2026-05-18 13:30:07.750856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4c6eac973b'
down_revision: Union[str, Sequence[str], None] = 'cd8238885b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('companies', sa.Column('hashed_password', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.add_column('workers', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('workers', sa.Column('hashed_password', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_workers_email'), 'workers', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_email'), table_name='workers')
    op.drop_column('workers', 'hashed_password')
    op.drop_column('workers', 'email')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_column('companies', 'hashed_password')
    op.drop_column('companies', 'email')
    # ### end Alembic commands ###
