"""New column in table jobs for salary range

Revision ID: eb6d7e358fd4
Revises: 5f8f3573446f
Create Date: 2026-06-06 18:15:21.405028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6d7e358fd4'
down_revision: Union[str, Sequence[str], None] = '5f8f3573446f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary_low', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_high', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'salary_high')
    op.drop_column('jobs', 'salary_low')
    # ### end Alembic commands ###
