"""Job description column added

Revision ID: 0a7493c49d21
Revises: a1f7034a5fbd
Create Date: 2026-06-08 18:39:47.305412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a7493c49d21'
down_revision: Union[str, Sequence[str], None] = 'a1f7034a5fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('jobs', 'experience',
               existing_type=postgresql.ENUM('junior', 'middle', 'senior', name='experiencelevel'),
               nullable=False,
               existing_server_default=sa.text("'junior'::experiencelevel"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'experience',
               existing_type=postgresql.ENUM('junior', 'middle', 'senior', name='experiencelevel'),
               nullable=True,
               existing_server_default=sa.text("'junior'::experiencelevel"))
    op.drop_column('jobs', 'description')
    # ### end Alembic commands ###
