"""New column jobs.location_id

Revision ID: 5f8f3573446f
Revises: 80554c8be451
Create Date: 2026-06-06 18:09:00.668728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f8f3573446f'
down_revision: Union[str, Sequence[str], None] = '80554c8be451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'location_id')
    # ### end Alembic commands ###
