"""new 'role' column in workers,companies table, attempt2

Revision ID: a9919c48bc63
Revises: e0cf411f46ac
Create Date: 2026-05-22 19:51:08.253776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9919c48bc63'
down_revision: Union[str, Sequence[str], None] = 'e0cf411f46ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('role', sa.String(length=10), server_default=sa.text("'company'"), nullable=True))
    op.add_column('workers', sa.Column('role', sa.String(length=10), server_default=sa.text("'worker'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'role')
    op.drop_column('companies', 'role')
    # ### end Alembic commands ###
